-- To select which schema or database to use
USE mavenfuzzyfactory;

-- To select all in website sessions
SELECT *
FROM website_sessions;

-- To display the log of the pages viewed by a user when they were on the ecommerce website in a session
SELECT *
FROM website_pageviews
WHERE website_session_id = 1059;

-- To view the revenue generated by a user per website session id
SELECT *
FROM orders
WHERE website_session_id = 1059;

-- To show all the utm sources and campaigns we have
SELECT DISTINCT
	utm_source,
	utm_campaign
FROM website_sessions;

-- My results keep showing a null value in a row so i wangt to permanently delete it.
DELETE 
FROM website_sessions
WHERE website_session_id IS NULL;

SELECT *
FROM website_sessions
WHERE website_session_id BETWEEN 1000 AND 5000;

-- utm_content is  used to store the name of a specific ad that is being run
-- count of website sessions to see which ads are driving the most sessions
-- We rename the distinct count of the website session id with an alias (sessions)
SELECT utm_content, COUNT(DISTINCT website_session_id) AS sessions
FROM website_sessions
WHERE website_session_id 
		BETWEEN 1000 AND 2000
GROUP BY utm_content -- or 1
ORDER BY sessions DESC; -- or 2


-- To bring in the orders table to take a look at the orders generated from each ads
-- I'm making use of alias for each table name also so the column names on the syntax is not too large when identifying them or specifying them
SELECT WS.utm_content, 
		COUNT(DISTINCT WS.website_session_id) AS sessions,
        COUNT(DISTINCT O.order_id) AS orders,
        COUNT(DISTINCT O.order_id)/COUNT(DISTINCT WS.website_session_id)*100 AS conversion_rate -- Session to Order conversion rate
FROM website_sessions AS WS
	LEFT JOIN orders as O
		ON WS.website_session_id = O.website_session_id
WHERE WS.website_session_id 
		BETWEEN 1000 AND 2000
GROUP BY utm_content -- or 1
ORDER BY sessions DESC; -- or 2


-- To conversion_rate cleaner and easily readable, you can use a subquery instead
-- MySQL does not allow you to reuse aliases in the same SELECT clause (unlike some other databases)
SELECT ads,
		sessions,
        orders,
        orders/sessions*100 AS conversion_rate
FROM(
	SELECT WS.utm_content AS ads, 
			COUNT(DISTINCT WS.website_session_id) AS sessions,
			COUNT(DISTINCT O.order_id) AS orders
	FROM website_sessions AS WS
		LEFT JOIN orders as O
			ON WS.website_session_id = O.website_session_id
	WHERE WS.website_session_id 
			BETWEEN 1000 AND 2000
	GROUP BY utm_content -- or 1
	ORDER BY sessions DESC -- or 2
) AS sub
ORDER BY 2 DESC;

-- Volume of website sessions by utm source, campaign and referring domain up till April 12, 2012
SELECT utm_source AS sources,
		utm_campaign AS campaign,
        http_referer AS refer_domain,
        COUNT(DISTINCTwebsite_session_id) AS website_sessions
FROM website_sessions
WHERE DATE(created_at) < '2012-04-12'
GROUP BY 1,2,3
ORDER BY 4 DESC;

-- Calculating converion rate from session to order on gsearch(source) nonbrand (campaign) from April 14, 2012 downward
SELECT COUNT(DISTINCT WS.website_session_id) AS sessions,
		COUNT(DISTINCT O.order_id) AS orders,
        COUNT(DISTINCT O.order_id)/COUNT(DISTINCT WS.website_session_id)*100 AS CVR
FROM website_sessions AS WS
	LEFT JOIN orders AS O
		ON WS.website_session_id = O.website_session_id
WHERE WS.created_at < '2012-04-14'
		AND WS.utm_source = 'gsearch'
        AND WS.utm_campaign = 'nonbrand';

-- Working with grouped dates
SELECT website_session_id,
		created_at,
        MONTH(created_at),
        WEEK(created_at),
        YEAR(created_at)
FROM website_sessions
WHERE website_session_id BETWEEN 100000 AND 115000; -- arbitary

SELECT YEAR(created_at),
        WEEK(created_at),
        MIN(DATE(created_at)), 
        COUNT(DISTINCT website_session_id)
FROM website_sessions
WHERE website_session_id 
	BETWEEN 100000 AND 115000 -- arbitary
GROUP BY 1,2;

-- Another testrun. I could not see my contributions in my profile